### ISSUE TITLE
Does measurement or consciousness determine quantum state? 

### ISSUE THREAD

**Issue by lindenquan** [eth-sri/silq#27]
I know it is not silq related question. I couldn't find a better place to ask the question. Hopefully, someone can help me with the question. Thanks in advance.

I know quantum states are in super positions. But How do we know it is the measurement determines the quantum state ? Could it be consciousness ? For example, we use tool measure the state of the quantum particle, but no one checked the result. 

I cannot prove it. But I have an assumption. The our consciousness might determines the quantum state not the measurement.

This is big different with Schrödinger's cat experiment. 
Case 1: Measurement determines the quantum state.
Then: When the device measures the radioactivity, then the quantum state is determined. So the state of cat is actually determined.
Case 2: Consciousness determines the quantum state.
Then: The measurement of radioactivity cannot determine the quantum state. So the cat is in superposition. The cat is alive and died at the same time.

**Comment by tgehr** [comment]
Disclaimer: I am not a physicist and my understanding may be off or out of date.

First, note that this thought experiment was proposed by Schrödinger in order to demonstrate the obvious absurdity of entangled macroscopic states. Not to say he was necessarily right, but I think it's good to know where he was coming from.

The radioactive atom, the measurement apparatus, the poison, the cat, the box and the observer outside of the box as well as the remainder of the universe are all part of the same quantum system and they interact with each other in many ways, therefore, they will quickly be entangled. (This is known as decoherence. It is the main obstacle for building quantum computers.)

As far as I know, it's still not settled whether this kind of decoherence causes macroscopic entanglement of the entire universe and (a) measurement is just the way entanglement looks "from the inside" to a classical observer, or (b) large-scale entanglement is unstable and decays quickly, such that the quantum system naturally evolves towards states with classical properties. (It's of course also possible that what's actually going on is some combinaton of (a) and (b).)

I don't think it makes much of a difference whether some of the subsystems are "conscious", but yes, if the universe works like (b) above, what may cause the stochasticity in measurement outcomes is that we do not model the complete system when we talk about a measurement. (Wave function collapse according to the Born rule is the same as what you get when you trace explicitly modeled parts of the environment, including the observer, out of the system, but the Born rule allows you to get away with not modeling those aspects.) Unitary time evolution is deterministic, so in this case it is the observer together with the remainder of the environment that determines the outcome of the measurement perfectly.

I.e., it's not really clear what would happen if we were able to put some observer/measurement device/cat in a box that does not have any interaction with the environment, whether the observer/macroscopic measurement device/cat itself would be enough to cause some sort of collapse or not. Maybe the state of the cat determines at which time it is killed by the decaying atom, or perhaps there might be macroscopic entanglement of the entire cat that only collapses when we open the box and it comes in contact with the environment. Personally, I think it's unlikely that observers or their "consciousness" deserve any sort of special status in terms of physics, the Born rule is just a tool that empirically allows us to match the theory to the way we observe experimental results in practice (i.e., we do not model the measurement apparatus or its human observer, because that would be too complicated).

The ongoing quest to build larger quantum computers might shed some light on this (though I think it's unlikely we will be able to simulate a full cat within a quantum computer).

I am closing this so it does not clutter the issue tracker, but feel free to keep discussing here.

**Comment by lindenquan** [comment]
Thanks very much tgehr. You gave a new view to understand quantum world. Thanks again.
