### ISSUE TITLE
Dependency and Build File Error

### ISSUE THREAD

**Issue by vinamramunot-tech** [eth-sri/silq#3]
# Problem Statement

Hi Everyone, I am trying to install silq in macOS environment and I am facing issues with running the dependencies.sh and build.sh file. 

## Environment
1. zsh shell
2. bash shell

## Error Image
<img width="531" alt="Screen Shot 2020-06-18 at 12 50 39 PM" src="https://user-images.githubusercontent.com/56406734/84990508-d82d9a00-b162-11ea-9bc5-32780a82e8a0.png">

Please guide me! 🙏

**Comment by WebFreak001** [comment]
it seems you don't have wget installed (see first output line) which causes the dmd zip not to be downloaded and the build command to fail. `wget` is a command line tool needed to download files from the internet, in this case downloading the D compiler for this project.

See https://stackoverflow.com/questions/33886917/how-to-install-wget-in-macos how to install wget through brew or MacPorts and then rerun your commands. I would really recommend you to do it this way. You might run into an issue of `unzip` then not being found, which you can install with the same command as with wget, just instead of wget with `unzip` as argument.

If you don't have brew or MacPorts and don't want to install them however you can also just manually download dmd from https://dlang.org/download.html#dmd and simply extract it so the dmd2 folder is inside the project folder. Then you just only use `build.sh`. The `dependencies.sh` file references v2.088.1, so to avoid build issues you might want to get http://downloads.dlang.org/releases/2019/dmd.2.088.1.osx.zip instead of the latest version.

**Comment by vinamramunot-tech** [comment]
It worked! Thank you!
